import {
  CAP_NHAT_NGUOI_DUNG,
  THEM_NGUOI_DUNG,
  XOA_NGUOI_DUNG,
  LAY_NGUOI_DUNG,
} from "../types/QuanLyNguoiDungType";

const userData = [
  {
    id: "01",
    surname: "Tran",
    name: "Van Kien",
    email: "example@gmail.com",
    phone: "0333333333",
    nation: "Việt Nam",
    city: "TP HCM",
    district: "A",
    commune: "A",
    image: "",
    address: "Quan 3",
    role: "Super Admin",
    position: "A",
    part: "A",
    branch: "A",
    state: true,
    dateCreate: "2/3/2022",
  },
  {
    id: "02",
    surname: "Tran",
    name: "Van Kien",
    email: "example@gmail.com",
    phone: "0333333333",
    nation: "Việt Nam",
    city: "TP HCM",
    district: "A",
    commune: "A",
    image: "",
    address: "Quan 3",
    role: "Super Admin",
    position: "A",
    part: "A",
    branch: "A",
    state: false,
    dateCreate: "2/3/2022",
  },
  {
    id: "03",
    surname: "Tran",
    name: "Van Tung",
    email: "example@gmail.com",
    phone: "0333333333",
    nation: "Việt Nam",
    city: "TP HCM",
    district: "A",
    commune: "A",
    image: "",
    address: "Quan 3",
    role: "Super Admin",
    position: "A",
    part: "A",
    branch: "A",
    state: true,
    dateCreate: "2/3/2022",
  },
  {
    id: "04",
    surname: "Tran",
    name: "Van Quy",
    email: "xinchao@gmail.com",
    phone: "0333333333",
    nation: "Việt Nam",
    city: "TP HCM",
    district: "A",
    commune: "A",
    image: "",
    address: "Quan 3",
    role: "Super Admin",
    position: "A",
    part: "A",
    branch: "A",
    state: true,
    dateCreate: "2/3/2022",
  },
  {
    id: "05",
    surname: "Tran",
    name: "Van Quy",
    email: "example@gmail.com",
    phone: "0333333333",
    nation: "Việt Nam",
    city: "TP HCM",
    district: "A",
    commune: "A",
    image: "",
    address: "Quan 3",
    role: "Super Admin",
    position: "A",
    part: "A",
    branch: "A",
    state: true,
    dateCreate: "2/3/2022",
  },
  {
    id: "06",
    surname: "Nguyen",
    name: "Van Quy",
    email: "example@gmail.com",
    phone: "0333333333",
    nation: "Việt Nam",
    city: "TP HCM",
    district: "A",
    commune: "A",
    image: "",
    address: "Quan 3",
    role: "Super Admin",
    position: "A",
    part: "A",
    branch: "A",
    state: true,
    dateCreate: "2/3/2022",
  },
  {
    id: "07",
    surname: "Tran",
    name: "Van Quy",
    email: "example@gmail.com",
    phone: "0333333333",
    nation: "Việt Nam",
    city: "TP HCM",
    district: "A",
    commune: "A",
    image: "",
    address: "Quan 3",
    role: "Super Admin",
    position: "A",
    part: "A",
    branch: "A",
    state: false,
    dateCreate: "2/3/2022",
  },
  {
    id: "08",
    surname: "Tran",
    name: "Van Quy",
    email: "example@gmail.com",
    phone: "0333333333",
    nation: "Việt Nam",
    city: "TP HCM",
    district: "A",
    commune: "A",
    image: "",
    address: "Quan 3",
    role: "Super Admin",
    position: "A",
    part: "A",
    branch: "A",
    state: true,
    dateCreate: "2/3/2022",
  },
  {
    id: "09",
    surname: "Tran",
    name: "Van Quy",
    email: "example@gmail.com",
    phone: "0333333333",
    nation: "Việt Nam",
    city: "TP HCM",
    district: "A",
    commune: "A",
    image: "",
    address: "Quan 3",
    role: "Super Admin",
    position: "A",
    part: "A",
    branch: "A",
    state: true,
    dateCreate: "2/3/2022",
  },
  {
    id: "10",
    surname: "Tran",
    name: "Van Quy",
    email: "example@gmail.com",
    phone: "0333333333",
    nation: "Việt Nam",
    city: "TP HCM",
    district: "A",
    commune: "A",
    image: "",
    address: "Quan 3",
    role: "Super Admin",
    position: "A",
    part: "A",
    branch: "A",
    state: false,
    dateCreate: "2/3/2022",
  },
  {
    id: "11",
    surname: "Tran",
    name: "Van Quy",
    email: "example@gmail.com",
    phone: "0333333333",
    nation: "Việt Nam",
    city: "TP HCM",
    district: "A",
    commune: "A",
    image: "",
    address: "Quan 3",
    role: "Super Admin",
    position: "A",
    part: "A",
    branch: "A",
    state: true,
    dateCreate: "2/3/2022",
  },
  {
    id: "12",
    surname: "Tran",
    name: "Van Quy",
    email: "example@gmail.com",
    phone: "0333333333",
    nation: "Việt Nam",
    city: "TP HCM",
    district: "A",
    commune: "A",
    image: "",
    address: "Quan 3",
    role: "Super Admin",
    position: "A",
    part: "A",
    branch: "A",
    state: true,
    dateCreate: "2/3/2022",
  },
  {
    id: "13",
    surname: "Tran",
    name: "Van Quy",
    email: "example@gmail.com",
    phone: "0333333333",
    nation: "Việt Nam",
    city: "TP HCM",
    district: "A",
    commune: "A",
    image: "",
    address: "Quan 3",
    role: "Super Admin",
    position: "A",
    part: "A",
    branch: "A",
    state: true,
    dateCreate: "2/3/2022",
  },
  {
    id: "14",
    surname: "Tran",
    name: "Van Quy",
    email: "example@gmail.com",
    phone: "0333333333",
    nation: "Việt Nam",
    city: "TP HCM",
    district: "A",
    commune: "A",
    image: "",
    address: "Quan 3",
    role: "Super Admin",
    position: "A",
    part: "A",
    branch: "A",
    state: true,
    dateCreate: "2/3/2022",
  },

  {
    id: "15",
    surname: "Tran",
    name: "Van Quy",
    email: "example@gmail.com",
    phone: "0333333333",
    nation: "Việt Nam",
    city: "TP HCM",
    district: "A",
    commune: "A",
    image: "",
    address: "Quan 3",
    role: "Super Admin",
    position: "A",
    part: "A",
    branch: "A",
    state: true,
    dateCreate: "2/3/2022",
  },
  {
    id: "16",
    surname: "Nguyen",
    name: "Van Quy",
    email: "example@gmail.com",
    phone: "0333333333",
    nation: "Việt Nam",
    city: "TP HCM",
    district: "A",
    commune: "A",
    image: "",
    address: "Quan 3",
    role: "Super Admin",
    position: "A",
    part: "A",
    branch: "A",
    state: true,
    dateCreate: "2/3/2022",
  },
  {
    id: "17",
    surname: "Nguyen",
    name: "Van Quy",
    email: "example@gmail.com",
    phone: "0333333333",
    nation: "Việt Nam",
    city: "TP HCM",
    district: "A",
    commune: "A",
    image: "",
    address: "Quan 3",
    role: "Super Admin",
    position: "A",
    part: "A",
    branch: "A",
    state: true,
    dateCreate: "2/3/2022",
  },
  {
    id: "18",
    surname: "Nguyen",
    name: "Van Quy",
    email: "example@gmail.com",
    phone: "0333333333",
    nation: "Việt Nam",
    city: "TP HCM",
    district: "A",
    commune: "A",
    image: "",
    address: "Quan 3",
    role: "Super Admin",
    position: "A",
    part: "A",
    branch: "A",
    state: true,
    dateCreate: "2/3/2022",
  },
  {
    id: "19",
    surname: "Nguyen",
    name: "Van Quy",
    email: "example@gmail.com",
    phone: "0333333333",
    nation: "Việt Nam",
    city: "TP HCM",
    district: "A",
    commune: "A",
    image: "",
    address: "Quan 3",
    role: "Super Admin",
    position: "A",
    part: "A",
    branch: "A",
    state: true,
    dateCreate: "2/3/2022",
  },
  {
    id: "20",
    surname: "Nguyen",
    name: "Van Quy",
    email: "example@gmail.com",
    phone: "0333333333",
    nation: "Việt Nam",
    city: "TP HCM",
    district: "A",
    commune: "A",
    image: "",
    address: "Quan 3",
    role: "Super Admin",
    position: "A",
    part: "A",
    branch: "A",
    state: true,
    dateCreate: "2/3/2022",
  },
  {
    id: "21",
    surname: "Nguyen",
    name: "Van Quy",
    email: "example@gmail.com",
    phone: "0333333333",
    nation: "Việt Nam",
    city: "TP HCM",
    district: "A",
    commune: "A",
    image: "",
    address: "Quan 3",
    role: "Super Admin",
    position: "A",
    part: "A",
    branch: "A",
    state: true,
    dateCreate: "2/3/2022",
  },
  {
    id: "22",
    surname: "Nguyen",
    name: "Van Quy",
    email: "example@gmail.com",
    phone: "0333333333",
    nation: "Việt Nam",
    city: "TP HCM",
    district: "A",
    commune: "A",
    image: "",
    address: "Quan 3",
    role: "Super Admin",
    position: "A",
    part: "A",
    branch: "A",
    state: true,
    dateCreate: "2/3/2022",
  },
  {
    id: "23",
    surname: "Nguyen",
    name: "Van Quy",
    email: "example@gmail.com",
    phone: "0333333333",
    nation: "Việt Nam",
    city: "TP HCM",
    district: "A",
    commune: "A",
    image: "",
    address: "Quan 3",
    role: "Super Admin",
    position: "A",
    part: "A",
    branch: "A",
    state: true,
    dateCreate: "2/3/2022",
  },
  {
    id: "24",
    surname: "Nguyen",
    name: "Van Quy",
    email: "example@gmail.com",
    phone: "0333333333",
    nation: "Việt Nam",
    city: "TP HCM",
    district: "A",
    commune: "A",
    image: "",
    address: "Quan 3",
    role: "Super Admin",
    position: "A",
    part: "A",
    branch: "A",
    state: true,
    dateCreate: "2/3/2022",
  },
  {
    id: "25",
    surname: "Nguyen",
    name: "Van Quy",
    email: "example@gmail.com",
    phone: "0333333333",
    nation: "Việt Nam",
    city: "TP HCM",
    district: "A",
    commune: "A",
    image: "",
    address: "Quan 3",
    role: "Super Admin",
    position: "A",
    part: "A",
    branch: "A",
    state: true,
    dateCreate: "2/3/2022",
  },
  {
    id: "26",
    surname: "Nguyen",
    name: "Van Quy",
    email: "example@gmail.com",
    phone: "0333333333",
    nation: "Việt Nam",
    city: "TP HCM",
    district: "A",
    commune: "A",
    image: "",
    address: "Quan 3",
    role: "Super Admin",
    position: "A",
    part: "A",
    branch: "A",
    state: true,
    dateCreate: "2/3/2022",
  },
];

const stateDefault = {
  users: userData,
  user: {},
};

export const QuanLyNguoiDungReducer = (state = stateDefault, action) => {
  switch (action.type) {
    case XOA_NGUOI_DUNG:
      return {
        ...stateDefault,
        users: state.users.filter((user) => user.id !== action.payload),
      };
    case LAY_NGUOI_DUNG:
      return {
        ...stateDefault,
        user: action.payload,
      };
    case THEM_NGUOI_DUNG:
      return {
        ...stateDefault,
        users: [...state.users, action.payload],
      };
    case CAP_NHAT_NGUOI_DUNG:
      const _users = [...state.users];
      const index = _users.findIndex((user) => user.id === action.payload.id);
      _users[index] = action.payload;
      return {
        ...stateDefault,
        users: _users,
      };
    default:
      return state;
  }
};
