export const DANG_NHAP="DANG_NHAP";
export const XOA_NGUOI_DUNG="XOA_NGUOI_DUNG";
export const LAY_NGUOI_DUNG="LAY_NGUOI_DUNG";
export const THEM_NGUOI_DUNG="THEM_NGUOI_DUNG";
export const CAP_NHAT_NGUOI_DUNG="CAP_NHAT_NGUOI_DUNG";
